### ISSUE TITLE
error installing requirements.txt

### ISSUE THREAD

**Issue by J-Ai-57** [newgenai79/StableAnimator#1]
(venv) D:\ai\StableAnimator>pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu124
ERROR: triton-3.0.0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

**Comment by nitinmukesh** [comment]
What is your python version?
python --version

I mentioned in video that the wheel is for 3.10. I can provide wheel for other python version

**Comment by J-Ai-57** [comment]
I have 3:11:10 should I go back to 3:10:11

**Comment by nitinmukesh** [comment]
3.10 should work.

However if you want to keep the python 3.11, update requirements.txt with this link against triton
https://huggingface.co/datasets/newgenai79/Windows_wheels/resolve/main/TRITON/triton-3.0.0-cp311-cp311-win_amd64.whl?download=true

**Comment by J-Ai-57** [comment]
once again...success! Thanks again

**Comment by J-Ai-57** [comment]
D:\ai\StableAnimator\inference\animation1>ffmpeg -i target.mp4 -q:v 1 -start_number 0 target_images/frame_%d.png
'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.

**Comment by J-Ai-57** [comment]
do I need to install ffmpeg? If so, root level or in the venv?

**Comment by nitinmukesh** [comment]
Search for ffmpeg in my YouTube channel. There is installation guide

It need to be installed globally in Windows

**Comment by J-Ai-57** [comment]
ok

**Comment by J-Ai-57** [comment]
great! all working, just wondered how to extract the files into faces folder after this error:
Traceback (most recent call last):
  File "D:\ai\StableAnimator\inference_basic.py", line 253, in <module>
    face_model = FaceModel()
                 ^^^^^^^^^^^
  File "D:\ai\StableAnimator\animation\modules\face_model.py", line 11, in __init__
    self.app = FaceAnalysis(
               ^^^^^^^^^^^^^
  File "D:\ai\StableAnimator\venv\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by nitinmukesh** [comment]
You don't need to extract faces. That is required only for training the model.
Is the inference not working?

**Comment by nitinmukesh** [comment]
If you are facing problem refer this
https://github.com/Francis-Rings/StableAnimator/issues/22

**Comment by J-Ai-57** [comment]
all but the inference is working. This the error:
D:\ai\StableAnimator>venv\scripts\activate

(venv) D:\ai\StableAnimator>command_basic_infer.bat

(venv) D:\ai\StableAnimator>set CUDA_VISIBLE_DEVICES=0

(venv) D:\ai\StableAnimator>python inference_basic.py  --pretrained_model_name_or_path="./checkpoints/stable-video-diffusion-img2vid-xt"  --output_dir="./outputs"  --validation_control_folder="./inference/animation1/poses"  --validation_image="./inference/animation1/reference.png"  --width=512  --height=512  --fps=25  --guidance_scale=3.0  --num_inference_steps=25  --posenet_model_name_or_path="./checkpoints/Animation/pose_net.pth"  --face_encoder_model_name_or_path="./checkpoints/Animation/face_encoder.pth"  --unet_model_name_or_path="./checkpoints/Animation/unet.pth"  --tile_size=16  --overlap=4  --noise_aug_strength=0.02  --frames_overlap=4  --decode_chunk_size=4  --gradient_checkpointing
D:\ai\StableAnimator\venv\Lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
D:\ai\StableAnimator\venv\Lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
D:\ai\StableAnimator\venv\Lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
D:\ai\StableAnimator\venv\Lib\site-packages\albumentations\__init__.py:24: UserWarning: A new version of Albumentations is available: 1.4.24 (you have 1.4.22). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
Start Time: 2024-12-28 13:15:03
download_path: checkpoints\models\antelopev2
Downloading checkpoints\models\antelopev2.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip...
100%|████████████████████| 352210/352210 [00:31<00:00, 11201.99KB/s]
Traceback (most recent call last):
  File "D:\ai\StableAnimator\inference_basic.py", line 253, in <module>
    face_model = FaceModel()
                 ^^^^^^^^^^^
  File "D:\ai\StableAnimator\animation\modules\face_model.py", line 11, in __init__
    self.app = FaceAnalysis(
               ^^^^^^^^^^^^^
  File "D:\ai\StableAnimator\venv\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by nitinmukesh** [comment]
Yeah it's the error with the original code as files do not extract correctly.

Download the files from here and put in local folder
https://huggingface.co/FrancisRing/StableAnimator/tree/main/models/antelopev2

Refer the readme
> All the weights should be organized in checkpoints as follows

**Comment by J-Ai-57** [comment]
I have the files in the StableAnimator/Models/AntelopeV2 folder already, yet it downloads them to the checkpoints folder when command_basic_infer.bat is used

**Comment by nitinmukesh** [comment]
Let me install again on my laptop. Will get back to you

**Comment by nitinmukesh** [comment]
Give me the assets you are testing with so I can quickly verify with them. Zip and upload here.

**Comment by J-Ai-57** [comment]
[reference.zip](https://github.com/user-attachments/files/18265741/reference.zip)

**Comment by J-Ai-57** [comment]
[poses.zip](https://github.com/user-attachments/files/18265745/poses.zip)

**Comment by J-Ai-57** [comment]
https://github.com/user-attachments/assets/dc352119-024f-432f-b3fb-611028dd0332

**Comment by J-Ai-57** [comment]
[target.zip](https://github.com/user-attachments/files/18265775/target.zip)

**Comment by nitinmukesh** [comment]
Working fine with fewer frames.
![image](https://github.com/user-attachments/assets/b4af2666-e26b-4222-bae1-d75b5c61272c)



It seems one of the reference image have problem. Try with fewer frames, like 20 frames in poses folder.
 Also post issue in https://github.com/Francis-Rings/StableAnimator/issues with all assets

https://github.com/user-attachments/assets/80e12b76-e30c-4920-a80e-e4dcc6992570

**Comment by J-Ai-57** [comment]
cant play your video extraction, can you resend. Also for me even with just 19 frames it just downloads Antelope v2 and then the Error.

**Comment by nitinmukesh** [comment]
Right click on video and copy video address. Download the link using any download manager.

**Comment by nitinmukesh** [comment]
Also check the tree structure in checkpoints folder with this

```
C:\ai1\StableAnimator\checkpoints>tree /F
Folder PATH listing for volume Windows-SSD
Volume serial number is CE9F-A6AE
C:.
│   .gitattributes
│   config.json
│   inference.zip
│   README.md
│
├───Animation
│       face_encoder.pth
│       pose_net.pth
│       unet.pth
│
├───assets
│   ├───figures
│   │       case-17.gif
│   │       case-18.gif
│   │       case-24.gif
│   │       case-35.gif
│   │       case-42.gif
│   │       case-45.gif
│   │       case-46.gif
│   │       case-47.gif
│   │       case-5.gif
│   │       case-61.gif
│   │       framework.jpg
│   │
│   └───gif
│           case-35.gif
│           case-42.gif
│
├───DWPose
│       dw-ll_ucoco_384.onnx
│       yolox_l.onnx
│
├───models
│   └───antelopev2
│           .gitattributes
│           1k3d68.onnx
│           2d106det.onnx
│           genderage.onnx
│           glintr100.onnx
│           scrfd_10g_bnkps.onnx
│
└───stable-video-diffusion-img2vid-xt
    │   .gitattributes
    │   comparison.png
    │   LICENSE.md
    │   model_index.json
    │   output_tile.gif
    │   README.md
    │   svd_xt.safetensors
    │   svd_xt_image_decoder.safetensors
    │
    ├───feature_extractor
    │       preprocessor_config.json
    │
    ├───image_encoder
    │       config.json
    │       model.fp16.safetensors
    │       model.safetensors
    │
    ├───scheduler
    │       scheduler_config.json
    │
    ├───unet
    │       config.json
    │       diffusion_pytorch_model.fp16.safetensors
    │       diffusion_pytorch_model.safetensors
    │
    └───vae
            config.json
            diffusion_pytorch_model.fp16.safetensors
            diffusion_pytorch_model.safetensors
```

**Comment by J-Ai-57** [comment]
any download manager suggestions?

**Comment by nitinmukesh** [comment]
I use Free Download manager
https://www.freedownloadmanager.org/

**Comment by J-Ai-57** [comment]
looks great, My document tree matches yours

**Comment by nitinmukesh** [comment]
Out of ideas. Only suggestion is to delete and install again.
Also post this issue here
https://github.com/Francis-Rings/StableAnimator/issues

**Comment by J-Ai-57** [comment]
ok

**Comment by J-Ai-57** [comment]
I will go to python 3:10:11

**Comment by nitinmukesh** [comment]
I don't think it has anything to do with python version.

Can you try this

Copy the antelopev2 folder from here, do not cut
checkpoints/models/antelopev2

and paste in following 2 folders
checkpoints
and 
models

Also put files in antelopev2

to
StableAnimator/models/antelopev2

**Comment by nitinmukesh** [comment]
After above it should look like

StableAnimator/models/antelopev2/*.onnx
checkpoints/models/antelopev2/*.onnx
checkpoints/antelopev2/*.onnx

**Comment by nitinmukesh** [comment]
Also share this file here, just copy paste the content in comment
StableAnimator\animation\modules\face_model.py

**Comment by J-Ai-57** [comment]
re-installed from start, had to use your Triton link: https://huggingface.co/datasets/newgenai79/Windows wheels/resolve/main/TRITON/triton-3.0.0-cp311-cp311-win_amd64.whl?download=true.... now all working. I had used Francis's requirements file in my confusion. Now its working great!! Thank you again!
